export const LAYER_TABLE = {
  BACKGROUND: "bg",
  BACKGROUND_DETAIL: "ol",
  BICYCLE: "br",
  CADASTRAL: "lp",
  CTT: "ctt",
  HIKING_TRAIL: "ar",
  PANORAMA: "pr",
  POI_KOREAN: "lko",
  TRANSIT: "ts",
  KOREAN: "lko",
  ENGLISH: "len",
  CHINESE: "lzh",
  JAPANESE: "lja",
};
