on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Please refer to [CHANGELOG.md](https://github.com/DongKyuuuu/vue3-naver-maps/blob/main/CHANGELOG.md) for details.
